number = int(input("Enter A Number of Your choice:"))
print("1 times",number,"is",number*1)
print("2 times",number,"is",number*2)
print("3 times",number,"is",number*3)
print("4 times",number,"is",number*4)
print("5 times",number,"is",number*5)
print("6 times",number,"is",number*6)
print("7 times",number,"is",number*7)
print("8 times",number,"is",number*8)
print("9 times",number,"is",number*9)
print("10 times",number,"is",number*10)
print("11 times",number,"is",number*11)
print("12 times",number,"is",number*12)
print(number,"To the power of 1 is",number)
print(number,"To the power of 2 is",number*number)
print(number,"To the power of 3 is",number*number*number)
print(number,"To the power of 4 is",number*number*number*number)
print(number,"To the power of 5 is",number*number*number*number*number)
print(number,"To the power of 6 is",number*number*number*number*number*number)
print(number,"To the power of 7 is",number*number*number*number*number*number*number)
print(number,"To the power of 8 is",number*number*number*number*number*number*number*number)
print(number,"To the power of 9 is",number*number*number*number*number*number*number*number*number)
print(number,"To the power of 10 is",number*number*number*number*number*number*number*number*number*number)
print(number,"To the power of 11 is",number*number*number*number*number*number*number*number*number*number*number)
print(number,"To the power of 12 is",number*number*number*number*number*number*number*number*number*number*number*number)