pig1 = input("Enter the name for a pig:")
pig2 = input("Enter the name for a pig:")
pig3 = input("Enter the name for a pig:")
pig4 = input("Enter the name for a pig:")
build1 = input("Enter a building material:")
build2 = input("Enter a building material:")
build3 = input("Enter a building material:")
name4= input("enter a name for a wolf:")
print("There once were three little pigs. The first pig was called",pig1," the second was called",pig2,"and the third was called", pig3,". The first house was made from",build1,". The second house was made from",build2,". The third house was made from",build3,". The big bad wolf was called",name4,". The big bad wolf blew down the first two houses. He could not destroy the third house made from bricks. The pigs lived happily ever after.") 
